name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    -name: Buildx
      id: buildx
      uses: docker/setupbuildx-action@v1

    -name: DockerHub login
      uses: docker/login-action@v1
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASS}}

    -name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: dvsoft/dockettest:latest
